USE [master]
GO

/****** Object:  Database [SensitiveWords.SanitizerDb]    Script Date: 27 Feb 2026 08:57:18 ******/
CREATE DATABASE [SensitiveWords.SanitizerDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SensitiveWords.SanitizerDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\SensitiveWords.SanitizerDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SensitiveWords.SanitizerDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER01\MSSQL\DATA\SensitiveWords.SanitizerDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SensitiveWords.SanitizerDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET RECOVERY FULL 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET  MULTI_USER 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET QUERY_STORE = ON
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [SensitiveWords.SanitizerDb] SET  READ_WRITE 
GO


